package ajedrez.modelo;

public enum EnumEstadoDeJuego {
	SIN_ESTADO,
	SIN_PARTIDA,
	PARTIDA_ACTIVA_EN_JUEGO,
	PARTIDA_ACTIVA_EN_JAQUE,
	PARTIDA_ACTIVA_EN_CORONACION,
	EN_PEDIDO_DE_CAMBIO_DE_COLOR,
	EN_PEDIDO_DE_TABLA,
	PARTIDA_FINALIZADA_POR_ABANDONO,
	PARTIDA_FINALIZADA_POR_JAQUE_MATE,
	PARTIDA_FINALIZADA_POR_TABLA
}